apiVersion: v1
kind: Namespace
metadata:
  name: {{namespace}}
  labels:
    name: {{namespace}}
    usage: redis-demo

---
kind: Pod
apiVersion: v1
metadata:
  name: redis-instance
  namespace: {{namespace}}
  labels:
    app: redis
spec:
  containers:
    - name: redis-0
      image: redis:6.0.8-alpine3.12
      imagePullPolicy: Always
      ports:
        - containerPort: 6379
    - name: redis-exporter-0
      image: oliver006/redis_exporter:v1.11.1-alpine
      imagePullPolicy: Always
      ports:
        - containerPort: 9121
          name: metrics
          protocol: TCP

---
kind: Service
apiVersion: v1
metadata:
  name: my-redis-metrics
  namespace: {{namespace}}
  annotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: redis
  clusterIP: None
  ports:
    - name: metrics
      port: 9121
      protocol: TCP
      targetPort: metrics